export interface Task {
  id: number;
  title: string;
  body: string;
  userId: number;
  status?: 'pending' | 'in-progress' | 'completed' | 'overdue';
  priority?: 'low' | 'medium' | 'high';
  dueDate?: string; // ISO date string
}

export interface CreateTaskDTO extends Omit<Task, 'id'> {
  // Omit id for creation as it will be generated by the server
}

export interface UpdateTaskDTO extends Partial<Task> {
  id: number; // id is required for updates
}

export interface TaskFilters {
  [key: string]: any; // allow arbitrary query params like title_like for JSONPlaceholder
  userId?: number;
  _sort?: keyof Task;
  _order?: 'asc' | 'desc';
  _page?: number;
  _limit?: number;
}